<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>close</name>
   <tag></tag>
   <elementGuidId>fdbca4f0-ff1c-41a8-acd4-8daab0c0ac9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-iCfLBT cCCBxe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;sc-khQdMy DizEx&quot;]/div[@class=&quot;sc-cNKpQo GPgWG sc-AjmZR itoLXo&quot;]/button[@class=&quot;sc-pVTma deOLqx sc-jrQzUz jzmecn sc-iAKVOt cguyAl&quot;]/i[@class=&quot;sc-iCfLBT cCCBxe&quot;]</value>
   </webElementProperties>
</WebElementEntity>
